server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://119.29.130.179:3306/weixinapp?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root99
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 60000
      idle-timeout: 60000
      connection-timeout: 50000
      maximum-pool-size: 60
      minimum-idle: 10
  # HTTP ENCODING
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

mybatis:
  #配置SQL映射文件路径
  mapper-locations: classpath:com/example/*/dao/mapper/*.xml
  #配置别名
  type-aliases-package: com.example.*.entity
  #驼峰命名
  configuration:
    map-underscore-to-camel-case: true
app:
  workerId: 1
  dataCenterId: 2
